name: darth_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  file_picker: 6.2.0
  provider: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/shop/
    - assets/images/shop/potions/
    - assets/adventures/
    - assets/images/equipment/
    - assets/images/equipment/items/
    - assets/config/
    - assets/images/item-catcher/
